name: Crusher Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g crusher-cli@1.3.24

#     - name: Deploy to Heroku
#       env:
#         HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
#         HEROKU_APP_NAME: "crusher-test"
#       run: git push https://heroku:4061a111-a6e1-45ca-b299-2bfa71b94ac1@git.heroku.com/crusher-test.git master

    - name: RUN CLI Checks
      run: ./bin/run run --project_id=40  --crusher_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NSwidGVhbV9pZCI6MzQsImlhdCI6MTU5NDk5Mzg3MywiZXhwIjo1MTk0OTkwMjczfQ.5rf2rEkjh1mXb7OagnFDRvyY1qGxcFvp8naFmxgsaDk
